interact_online_tasks/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range,
)

from django.db.migrations.loader import MigrationLoader
from django.db.migrations.autodetector import MigrationAutodetector
from django.utils import timezone

import random



author = 'Johanna Gereke'

doc = """
INTERACT Online Tasks
"""


class Constants(BaseConstants):
    name_in_url = 'interact_online_tasks'
    players_per_group = None
    num_rounds = 1

#Fixed randomization: first position empty, so we can use "id_profile"
    dg_name1=[	' ',	'Anna',	'Mohammed',	'Xi-Wang',	'Antonio',	'Giovanni',	'Maria',	]
    dg_gen1=[	' ',	'She',	'He',	'He',	'He',	'He',	'She',	]
    dg_place1=[	' ',	'in Lombardia',	'in Marocco',	'in Cina',	'in Lombardia',	'in Lombardia',	'in Lombardia',	]
    dg_age1=[	' ',	'56',	'23',	'49',	'31',	'61',	'39',	]
    dg_name2=[	' ',	'Patricia',	'Giovanni',	'Anna',	'Alia',	'Patricia',	'Edenjevy',	]
    dg_gen2=[	' ',	'She',	'He',	'She',	'She',	'She',	'He',	]
    dg_place2=[	' ',	'nelle Filippine',	'in Lombardia',	'in Lombardia',	'in Marocco',	'nelle Filippine',	'nelle Filippine',	]
    dg_age2=[	' ',	'47',	'50',	'56',	'50',	'47',	'49',	]
    pd_name1=[	' ',	'Edenjevy',	'Anna',	'Sandra',	'Xing-Fu',	'Oana',	'Elena',	]
    pd_gen1=[	' ',	'He',	'She',	'She',	'He',	'She',	'She',	]
    pd_place1=[	' ',	'nelle Filippine',	'in Lombardia',	'in Perù',	'in Cina',	'in Romania',	'in Lombardia',	]
    pd_age1=[	' ',	'49',	'56',	'39',	'41',	'46',	'59',	]
    pd_altdec1=[	' ',	'partecipare',	'non partecipare',	'partecipare',	'partecipare',	'non partecipare',	'partecipare',	]
    pd_name2=[	' ',	'Francesco',	'Sabrina',	'Diego',	'Anis',	'Anna',	'Angelo',	]
    pd_gen2=[	' ',	'He',	'She',	'He',	'He',	'She',	'He',	]
    pd_place2=[	' ',	'in Lombardia',	'in Marocco',	'in Perù',	'in Marocco',	'in Lombardia',	'nelle Filippine',	]
    pd_age2=[	' ',	'24',	'45',	'52',	'18',	'25',	'46',	]
    pd_altdec2=[	' ',	'partecipare',	'non partecipare',	'non partecipare',	'partecipare',	'non partecipare',	'partecipare',	]
    trust_name1=[	' ',	'Loysa',	'Li Mei',	'Bogdan',	'Antonio',	'Angela',	'Francesco',	]
    trust_gen1=[	' ',	'She',	'She',	'He',	'He',	'She',	'He',	]
    trust_place1=[	' ',	'nelle Filippine',	'in Cina',	'in Romania',	'in Lombardia',	'nelle Filippine',	'in Lombardia',	]
    trust_age1=[	' ',	'23',	'40',	'27',	'44',	'23',	'37',	]
    trust_job=[	' ',	'nell’assistenza agli anziani',	'in un supermercato',	'in un supermercato',	'nell’assistenza agli anziani',	'in un supermercato',	'nell’assistenza agli anziani',	]
    trust_altdec1=[	'0',	'0.5',	'0',	'0.6',	'0.5',	'0',	'0',	]
    trust_name2=[	' ',	'Antonio',	'Anas',	'Anis',	'Sabrina',	'Alia',	'Loysa',	]
    trust_gen2=[	' ',	'He',	'He',	'He',	'She',	'She',	'She',	]
    trust_place2=[	' ',	'in Lombardia',	'in Marocco',	'in Marocco',	'in Marocco',	'in Marocco',	'nelle Filippine',	]
    trust_age2=[	' ',	'44',	'28',	'33',	'45',	'37',	'23',	]
    trust_activity=[	' ',	'e’ un rappresentante dei genitori nella classe di suo figlio.',	'fa volontariato nel campo estivo della Chiesa nel suo quartiere.',	'fa volontariato nel campo estivo della Moschea nel suo quartiere.',	'fa volontariato in un’associazione culturale del Marocco.',	'ama cucinare.',	'e’ un rappresentante dei genitori nella classe di suo figlio.',	]
    trust_altdec2=[	'0',	'0',	'0',	'0.5',	'0',	'0.6',	'0.5',	]
    threat_name=[	' ',	'Melvin',	'Giovanni',	'Fang Hua',	'Elena',	'Francesco',	'Maria',	]
    threat_gen=[	' ',	'He',	'He',	'She',	'She',	'He',	'She',	]
    threat_place=[	' ',	'nelle Filippine',	'in Lombardia',	'in Cina',	'in Lombardia',	'in Lombardia',	'in Lombardia',	]
    threat_age=[	' ',	'33',	'49',	'30',	'24',	'52',	'52',	]
    threat_altdec=[	' ',	'Prendere',	'Non prendere',	'Prendere',	'Non prendere',	'Prendere',	'Non prendere',	]

        #Other constants to be defined
    cc = 5
    dc = 8
    cd = 1
    dd = 3
    pd_infosell = c(0.50)
    pd_infobuy = c(0.50)
    minimum_age = 18
    maximum_age = 70

class Subsession(BaseSubsession):
    pass

class Group(BaseGroup):

    selected_individual_task = models.PositiveIntegerField()
    selected_pgg = models.PositiveIntegerField

    def select_paid_it(self):
        self.vote_individual_task = []
        for p in self.get_players():
            self.vote_individual_task.append(p.paid_individual_task)
        data1 = Counter(self.vote_individual_task)
        self.selected_individual_task= data1.most_common(1)[0][0]
        if self.selected_individual_task == 1:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_dg1']
        elif self.selected_individual_task == 2:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_dg2']
        elif self.selected_individual_task == 3:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_svoc']
        elif self.selected_individual_task == 4:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_svonc']
        elif self.selected_individual_task == 5:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_pdguess']
        elif self.selected_individual_task == 6:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_pd1']
        elif self.selected_individual_task == 7:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_pd2']
        elif self.selected_individual_task == 8:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_trustjob']
        elif self.selected_individual_task == 9:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_trustact']
        elif self.selected_individual_task == 10:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_threat']
        else:
            for p in self.get_players():
                p.payoff_individual_task = p.participant.vars['po_donation']

class Player(BasePlayer):
    id_profile = models.PositiveIntegerField()
    id_session = models.CharField()
    id_born =  models.PositiveIntegerField(choices=[
            [1,'A Milano'],
            [2,'In Italia, ma non a Milano'],
            [3,'Fuori dall’ Italia'],
            ],
        )

    def permanent_var(self):
        self.participant.vars['id_born'] = self.id_born
        #self.participant.vars['id_profile'] = self.id_profile
        #self.participant.vars['id_session'] = self.id_session

    choices = models.CharField(
            widget=widgets.RadioSelect(attrs={'readonly':'readonly'}),
    )

    #Pre Survey Questions
    city = models.CharField()

    residencetime = models.PositiveIntegerField(choices=[
        [1, 'meno di un anno'],
        [2, 'tra 1-3 anni'],
        [3, '4-10 anni'],
        [4, '11-15 anni'],
        [5, '16-20 anni'],
        [6, '21 anni o più'],
        ],
        )


    region = models.CharField()

    married = models.PositiveIntegerField(choices=[
       [1,'Single'],
       [2,'Sposato/a o convinvente'],
       [3,'Vedovo/a'],
       [4,'Separato/a o divorziato/a'],
    ],
    )

    children = models.PositiveIntegerField(choices=[
        [1,'No'],
        [2,'Si, 1 bambina/o'],
        [3,'Si, 2 bambini'],
        [4,'Si, 3 bambini'],
        [5,'Si, 4 bambini o più']
        ],
    )

    household = models.PositiveIntegerField(choices=[
        [1,'Vivo da solo/a'],
        [2,'Siamo in 2'],
        [3,'Siamo in 3'],
        [4,'Siamo in 4'],
        [5,'Siamo in 5'],
        [6,'Siamo in 6'],
        [7,'Siamo 7 o più'],
        ],
    )

    wallet = models.PositiveIntegerField(choices=[
        [1,'Quasi certo'],
        [2,'Molto probabile'],
        [3,'Non molto probabile'],
        [4,'Per nulla probabile'],
        ],
    )

    dec_risk = models.PositiveIntegerField(min=0, max=10)

    accomodation = models.PositiveIntegerField(choices=[
        [1,'È in affitto'],
        [2,'È di mia proprietà '],
        [3,'È di mia proprietà e sto pagando il mutuo'],
        [4,'(Non risponde)'],
        ],
    )

    savings = models.PositiveIntegerField(choices=[
        [1,'Risparmiato soldi'],
        [2,'Guadagnato lo stretto necessario'],
        [3,'Usato risparmi messi da parte in precedenza per le necessità quotidiane'],
        [4,'Preso denaro a prestito per le necessità quotidiane'],
        [5,'(Non sa)'],
        [6,'(Non risponde)'],
        ],
    )

    socialclass = models.PositiveIntegerField(choices=[
        [1,'Classe alta'],
        [2,'Classe medio-alta'],
        [3,'Classe medio-bassa'],
        [4,'Classe lavoratrice'],
        [5,'Classe bassa'],
        [6,'(Non sa)'],
        [7,'(Non risponde)'],
        ],
  )

    income = models.PositiveIntegerField(choices=[
        [1,'Meno di 15.000 Euro'],
        [2,'da 15.001 a 20.000 Euro'],
        [3,'da 20.001 a 25.000 Euro'],
        [4,'da 25.001 a 30.000 Euro'],
        [5,'da 30.001 a 35.000 Euro'],
        [6,'da 35.001 a 40.000 Euro'],
        [7,'da 40.001 a 47.000 Euro'],
        [8,'da 47.001 a 58.000 Euro'],
        [9,'da 58.001 a 80.000 Euro'],
        [10,'da 80.001 a 100.000 Euro'],
        [11,'da 100.001 a 150.000 Euro'],
        [12,'oltre 150.000 Euro'],
        [13,'(Non sa)'],
        [14,'(Non risponde)'],
        ],
    )

    attimm1 = models.PositiveIntegerField(choices=[
        [1,'Molto'],
        [2,'Abbastanza'],
        [3,'Poco'],

interact_online_tasks/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

interact_online_tasks/templates/interact_online_tasks/Informed_consent_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}

    <style type="text/css">
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    font-size: 110%;
    }
    </style>

{% endblock %}

{% block title %}

Consenso Informato

{% endblock %}

{% block content %}

<p> Questa ricerca è stata approvata dal comitato etico dell'Università Bocconi.</p>
<p>Prima di procedere, l'Università richiede che ogni partecipante dia il proprio
  esplicito consenso. </p>
  <div style="margin-bottom: 2em;"> <span style="display: none;">.</span> </div>

  <table class="table-condensed table-hover" style="width:50em; margin-top:0px; text-align: left;">
  <tr><td> Dichiaro di aver ricevuto una chiara spiegazione delle procedure e di non aver ulteriori domande.
  La mia partecipazione a questo studio è volontaria e sono consapevole di poter interrompere le attività
  in ogni momento. Il mio consenso non rappresenta una rinuncia ai miei diritti e non solleva l'Università Bocconi
  da alcuna responsabilità in caso di negligenza.
  <p></p>
  <p> <button class="btn btn-primary btn-large">Consento</button> </p>
</td> </tr>
</td></tr>
</table>



{% endblock %}

interact_online_tasks/templates/interact_online_tasks/PreSurvey0_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
Questionario 1
{% endblock %}

{% block content %}

<ul style="list-style-type:disc">
<li>  In quale regione? {% formfield player.region with label="" %} </li>
</ul>

<p><br></p>
    {% next_button %}
<p><br></p>

{% endblock %}

{% block scripts %}

<!-- <script>

$(function() {
  if($( "#id_born" ).val()==2){
    $( "#id_region" ).show();
  }else{
    $( "#id_region" ).hide();
  }
  $( "#id_born" ).change(function() {
      if($( "#id_born" ).val()==2){
        $( "#id_region" ).show();
      }else{
        $( "#id_region" ).hide();
      }
  });
}); -->

</script>

{% endblock %}

interact_online_tasks/templates/interact_online_tasks/PreSurvey1_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
Questionario 1
{% endblock %}

{% block content %}

<ul style="list-style-type:disc">
<li> In quale città vivi? {% formfield player.city with label="" %} </li>

<li> Da quanto tempo vivi in questa città? {% formfield player.residencetime with label="" %} </li>

<li> Dove sei nato/a? {% formfield player.id_born with label="" %} </li>

</ul>

<p><br></p>
    {% next_button %}
<p><br></p>

{% endblock %}

{% block scripts %}

<script>

$(function() {
  if($( "#id_born" ).val()==2){
    $( "#id_region" ).show();
  }else{
    $( "#id_region" ).hide();
  }
  $( "#id_born" ).change(function() {
      if($( "#id_born" ).val()==2){
        $( "#id_region" ).show();
      }else{
        $( "#id_region" ).hide();
      }
  });
});

</script>

{% endblock %}

interact_online_tasks/templates/interact_online_tasks/PreSurvey1b_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
Questionario 1
{% endblock %}

{% block content %}

<ul style="list-style-type:disc">
<li>  In quale regione? {% formfield player.region with label="" %} </li>
</ul>

<p><br></p>
    {% next_button %}
<p><br></p>

{% endblock %}

{% block scripts %}

<!-- <script>

$(function() {
  if($( "#id_born" ).val()==2){
    $( "#id_region" ).show();
  }else{
    $( "#id_region" ).hide();
  }
  $( "#id_born" ).change(function() {
      if($( "#id_born" ).val()==2){
        $( "#id_region" ).show();
      }else{
        $( "#id_region" ).hide();
      }
  });
}); -->

</script>

{% endblock %}

interact_online_tasks/templates/interact_online_tasks/Task1_A_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
<style>
.title{
   display: inline-block;
   height: 27px;
   border:solid 1px lightgrey;
   width: 40px;
   text-align: left;
}
</style>
{% endblock %}


{% block title %}

Attività  1A

{% endblock %}




{% block content %}


<p> Per la prima sessione di questa attività sei in coppia con {{dg_name1}}, che vive a Milano,
  è {% if dg_gen1 == "He" %} nato {% else %} nata {% endif %} {{dg_place1}} ed ha {{dg_age1}}
  anni.

    Per garantirne l’anonimato, non possiamo darti altre informazioni su di {% if dg_gen1 == "He" %}
    lui. {% else %} lei. {% endif %} </p>

<p> Decidi come dividere i 10 punti tra te e {{dg_name1}}. </p>

<p> Voglio tenere  <input type='number' name="dec_dg1" id="dec_dg1" onkeyup="updateMoneyLeft(this.value)" style="width: 3em" required> punti
  per me e dare <span id="deduction_span" class="title"><font color="black">&nbsp;</font></span> punti a {{dg_name1}}.</p>

<p><br></p>

    {% next_button %}
{% endblock %}


{% block scripts %}

    <!-- define a script -->


    <script>
           var player_money=document.getElementById("dec_dg1").value;

           function updateMoneyLeft(moneySpent){
                if(moneySpent>10){
                    document.getElementById("dec_dg1").value = 10;
                    moneySpent=10;
                }
                document.getElementById("deduction_span").innerHTML = 10 - moneySpent;
           }


    </script>
{% endblock %}

interact_online_tasks/templates/interact_online_tasks/Task1_B_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
<style>
.title{
   display: inline-block;
   height: 27px;
   border:solid 1px lightgrey;
   width: 40px;
   text-align: left;
}
</style>
{% endblock %}


{% block title %}

Attività  1B

{% endblock %}

{% block content %}

<p> Ora ripeterai l’attività con un’altra persona. Per questa seconda sessione sei
  in coppia con {{dg_name2}}, che vive a Milano, è {% if dg_gen2 == "He" %}
  nato {% else %} nata {% endif %} {{dg_place2}} ed ha  {{dg_age2}} anni.
    Per garantirne l’anonimato, non possiamo darti altre informazioni su di {% if dg_gen2 == "He" %}
    lui. {% else %} lei. {% endif %} </p>

<p> Decidi come dividere i 10 punti tra te e {{dg_name2}}. </p>

<p> Voglio tenere  <input type='number' name="dec_dg2" id="dec_dg2" onkeyup="updateMoneyLeft(this.value)" style="width: 3em" required> punti
  per me e dare <span id="deduction_span" class="title"><font color="black">&nbsp;</font></span> punti
a {{dg_name2}}.</p>

<p><br></p>

{{ form.dec_dg2.errors }}

    {% next_button %}
{% endblock %}


{% block scripts %}
    <script>
           var player_money=document.getElementById("dec_dg2").value;
           function updateMoneyLeft(moneySpent){
                if(moneySpent>10){
                    document.getElementById("dec_dg2").value = 10;
                    moneySpent=10;
                }
                document.getElementById("deduction_span").innerHTML = 10 - moneySpent;
           }
    </script>
{% endblock %}

interact_online_tasks/templates/interact_online_tasks/Task3A_choice_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Decision task 3A
{% endblock %}

{% block styles %}

<style type="text/css">
table, th, td {
border: 1px solid black;
border-collapse: collapse;
font-size: 100%;
text-align: center;
}

    #wrapper {
        position: relative;
        width: 800px;
        height:500px;
    }

    #top {
        position: relative;
        top: 0;
        width: 100%;
        height: 50%;
        /*background: red;*/
        padding: 2%;
    }

    #centerleft {
        position: absolute;
        float:center;
        left: 0%;
        width: 50%;
        height: 50%;
        padding: 2%;
        /*background: green;*/
    }

    #centerright{
        position: absolute;
        float:center;
        left: 50%;
        width: 50%;
        height: 50%;
        padding: 2%;
        margin-top: 5%;
        /*background: blue;*/
    }


    </style>
{% endblock %}

{% block content %}

<div id="wrapper">

<div id="top">
  <p> Ora faremo la stessa attività con una persona specifica. Le tue opzioni sono riassunte nella tabella.
<details style="font-size: 100%">
    <summary style="outline:none"> <b>Clicca qui se vuoi leggere nuovamente le istruzioni.</b></summary>
    In questa attività sei in coppia con un’altra persona che chiameremo Z. Puoi decidere
    se vuoi partecipare ad un progetto comune con Z. Sia tu che l’altra persona potete
    decidere se partecipare o no. Il tuo guadagno dipende sia dalla tua decisione sia
    dalla decisione dell’altra persona.
    <ul style="font-size: 100%">
      <li> Se entrambi decidete di partecipare, entrambi ricevete {{Constants.cc }} punti.</li>
      <li> Se tu partecipi, e Z non partecipa, tu ricevi {{Constants.cd }} punti
     , mentre B riceve {{Constants.dc}} punti. </li>
      <li> Se tu non partecipi, e Z partecipa, tu ricevi {{Constants.dc }} punti,
          mentre Z riceve {{Constants.cd }} punti. </li>
      <li>Se entrambi decidete di non partecipare, entrambi ricevete {{Constants.dd }} punti.</li>
</ul>
</details>
</p>

<p> In particolare, sei in coppia con {{pd_name1}},
    che vive a Milano, è {% if pd_gen1 == "He" %} nato {% else %} nata {% endif %}
     {{pd_place1}}, ed ha {{pd_age1}} anni. </p>

<p>Prego, indica <u>cosa pensi {% if pd_gen1 == "He" %} lui {% else %} lei {% endif %}</u> abbia deciso di fare.
  Se indovini, riceverai 5 punti.
<p>  Pensi che {% if pd_gen1 == "He" %} lui {% else %} lei {% endif %} abbia deciso
  di Partecipare o Non partecipare? </p>
{% formfield player.dec_pdguess with label=""%}
</div>

<div id="centerleft">
  <p>Quanto sicuro sei di aver indovinato cosa ha deciso di fare {{pd_name1}}?</p>
  {% formfield player.dec_pdcertain with label=""%}
</div>

<div id="centerright">
 <table class="table-condensed table-hover" style="width:400px; margin-top:0px; text-align: center; font-size: 90%">
     <tr><td><b> Tu </b></td> <td><b> {{pd_name1}} </b> </td> <td> <b>Tu ricevi </b></td> <td><b>{{pd_name1}} riceve</b></td> </tr>
     <tr><td> Partecipare </td> <td> Partecipare </td> <td> {{Constants.cc }} punti </td> <td> {{Constants.cc }} punti </td></tr>
     <tr><td> Partecipare </td> <td> Non partecipare </td> <td> {{Constants.cd }} punto </td> <td> {{Constants.dc }} punti </td></tr>
     <tr><td> Non partecipare </td> <td> Partecipare </td> <td> {{Constants.dc }} punti </td> <td> {{Constants.cd }} punto </td></tr>
     <tr><td> Non partecipare </td> <td> Non partecipare </td> <td> {{Constants.dd }} punti </td> <td> {{Constants.dd }} punti </td></tr>
</table>

</div>
</div>


<p><br></p>
    {% next_button %}
<p><br></p>

{% endblock %}

interact_online_tasks/templates/interact_online_tasks/Task3B_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Attività  3B{% endblock %}

{% block styles %}

        <style type="text/css">
        table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        font-size: 100%;
        text-align: center;
        }
        </style>

{% endblock %}

{% block content %}

<p> Sei sempre in coppia con {{pd_name1}}, che vive a Milano, è {% if pd_gen1 == "He" %}
  nato {% else %} nata {% endif %} {{pd_place1}}, ed ha {{pd_age1}} anni. </p>

<p> Ora decidi cosa fare:  </p>
{% formfield player.dec_pd1 with label=""%}

<p><br></p>

 <table class="table-condensed table-hover" style="width:400px; margin-top:0px; text-align: center;">
   <tr><td><b> Tu </b></td> <td><b> {{pd_name1}} </b> </td> <td> <b>Tu ricevi </b></td> <td><b>{{pd_name1}} riceve</b></td> </tr>
   <tr><td> Partecipare </td> <td> Partecipare </td> <td> {{Constants.cc }} punti </td> <td> {{Constants.cc }} punti </td></tr>
   <tr><td> Partecipare </td> <td> Non Partecipare </td> <td> {{Constants.cd }} punto </td> <td> {{Constants.dc }} punti </td></tr>
   <tr><td> Non Partecipare </td> <td> Partecipare </td> <td> {{Constants.dc }} punti </td> <td> {{Constants.cd }} punto </td></tr>
   <tr><td> Non Partecipare </td> <td> Non Partecipare </td> <td> {{Constants.dd }} punti </td> <td> {{Constants.dd }} punti </td></tr>
</table>
<p><br></p>
<details style="font-size: 100%">
    <summary style="outline:none"> <b>Clicca qui se vuoi leggere nuovamente le istruzioni.</b></summary>
    In questa attività sei in coppia con un’altra persona che chiameremo Z. Puoi decidere
    se vuoi partecipare ad un progetto comune con Z. Sia tu che l’altra persona potete
    decidere se partecipare o no. Il tuo guadagno dipende sia dalla tua decisione sia
    dalla decisione dell’altra persona.
    <ul style="font-size: 100%">
      <li> Se entrambi decidete di partecipare, entrambi ricevete {{Constants.cc }} punti.</li>
      <li> Se tu partecipi, e Z non partecipa, tu ricevi {{Constants.cd }} punti, mentre Z riceve {{Constants.dc}} punti. </li>
      <li> Se tu non partecipi, e Z partecipa, tu ricevi {{Constants.dc }} punti,
          mentre Z riceve {{Constants.cd }} punti. </li>
      <li>Se entrambi decidete di non partecipare, entrambi ricevete {{Constants.dd }} punti.</li>
</ul>
</details>
<p><br></p>
    {% next_button %}

{% endblock %}

interact_online_tasks/templates/interact_online_tasks/Task4B_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Attività  4B
{% endblock %}


{% block content %}

<p>Hai mandato {{dec_trustjob}} punti.</p>

<p>Questo ammontare viene triplicato. <b>Quindi, quanto riceve {{trust_name1}}?</b></p>
 {% formfield player.dec_trustcheckjob with label="" %}

<p><b>E quanto pensi che {{trust_name1}} ti rimanderà indietro? </b></p>
{% formfield player.dec_trustestimjob with label="" %}



    {% next_button %}

{% endblock %}

interact_online_tasks/templates/interact_online_tasks/Task4D_online.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
  Attività  4D
{% endblock %}


{% block content %}

<p> Hai mandato {{dec_trustactivity}} punti.</p>

<p>Questo ammontare viene triplicato. <b>Quindi, quanto riceve {{trust_name2}}?</b></p>
 {% formfield player.dec_trustcheckact with label="" %}

<p><b>E quanto pensi che {{trust_name2}} ti rimanderà indietro? </b></p>
{% formfield player.dec_trustestimact with label="" %}

    {% next_button %}

{% endblock %}